services:
  front-end:
    container_name: front-end
    build: ./front-end
    volumes:
      - front-volume:/var/www/html

  nginx:
    container_name: nginx-investiment
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - front-volume:/var/www/html
    depends_on:
      - front-end

volumes:
  front-volume: