services:
  nginx:
    container_name: nginx-reverse-proxy
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - front-volume:/var/www/html

  front-end:
    container_name: front-end
    build: ./front-end
    volumes:
      - front-volume:/var/www/html
    depends_on:
      - back-end

  back-end:
    build:
      context: ./investment
    container_name: back-end
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/investment
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

  database:
    image: postgres
    container_name: database
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=investment
    ports:
      - 5432:5432

volumes:
  front-volume: